version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/symfony_db?serverVersion=8.0 # 測試中 mysql://root:root@mysql:3306/symfony_db?serverVersion=5.7
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
    db:
        image: mysql:8.0.20
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci',
                  '--default-authentication-plugin=mysql_native_password']
        volumes:
            - ./mysql/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: symfony_db # ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: symfony_user # ${MYSQL_DATABASE}
            MYSQL_USER: symfony_password # ${MYSQL_USER}
            MYSQL_PASSWORD: root # ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
